version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./database:/app/database
      - ./ml:/app/ml
      - ./dataset:/app/dataset
    environment:
      - JWT_SECRET=super_secret_customer_iq_key_1234567890
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
